//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeTai.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeTai.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1195px_CJ_logo_svg {
            get {
                object obj = ResourceManager.GetObject("1195px-CJ_logo.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _300px_Thandieudaidiep20066nt {
            get {
                object obj = ResourceManager.GetObject("300px-Thandieudaidiep20066nt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _377_3777014_add_team_members_with_multi_user_accounts_multi {
            get {
                object obj = ResourceManager.GetObject("377-3777014_add-team-members-with-multi-user-accounts-multi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Anh_hung_xa_dieu_2016_66199 {
            get {
                object obj = ResourceManager.GetObject("Anh-hung-xa-dieu-2016-66199", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Anhhungxadieu {
            get {
                object obj = ResourceManager.GetObject("Anhhungxadieu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap biet_doi_san_moi {
            get {
                object obj = ResourceManager.GetObject("biet-doi-san-moi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap biet_doi_san_moi1 {
            get {
                object obj = ResourceManager.GetObject("biet-doi-san-moi1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ca_sau_tu_than {
            get {
                object obj = ResourceManager.GetObject("ca-sau-tu-than", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ca_sau_tu_than1 {
            get {
                object obj = ResourceManager.GetObject("ca-sau-tu-than1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cach_lam_banh_chuoi_chien_phong_gion_rum_thom_ngon_kho_cuong_tai_nha_7_1586257759_409_width512height288 {
            get {
                object obj = ResourceManager.GetObject("cach-lam-banh-chuoi-chien-phong-gion-rum-thom-ngon-kho-cuong-tai-nha-7-1586257759" +
                        "-409-width512height288", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cgv_1 {
            get {
                object obj = ResourceManager.GetObject("cgv-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ga {
            get {
                object obj = ResourceManager.GetObject("ga", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ham_quy {
            get {
                object obj = ResourceManager.GetObject("ham-quy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ham_quy1 {
            get {
                object obj = ResourceManager.GetObject("ham-quy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hoc_vien_quai_vat {
            get {
                object obj = ResourceManager.GetObject("hoc-vien-quai-vat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap huong_dan_lam_bap_rang_bo_bang_noi_inox_1 {
            get {
                object obj = ResourceManager.GetObject("huong-dan-lam-bap-rang-bo-bang-noi-inox-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_06_Credit_Card_1871423 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_06_Credit_Card_1871423", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_12_1751358 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_12_1751358", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_9_1517208 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_9_1517208", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_bill_discount_sale_shop_4177570 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_bill_discount_sale_shop_4177570", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_can_packaging_free_01_1777635 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_can-packaging-free-01_1777635", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_check_job_seeker_employee_unemployee_work_2620530 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_check_job_seeker_employee_unemployee_work_2620530", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_cinema_glasses_531883 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_cinema-glasses_531883", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_cloud_service_1312830 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_cloud_service_1312830", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_coffee_cup_package_d_free_09_1777634 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_coffee-cup-package-d-free-09_1777634", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_commandcustomfeatureselectronicscomputingservice_4904818 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_commandcustomfeatureselectronicscomputingservice_4904818", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_constr_add_card_1267307 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_constr_add_card_1267307", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_folder_job_seeker_employee_unemployee_work_2620522 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_folder_job_seeker_employee_unemployee_work_2620522", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_french_fries_snacks_fast_food_3558116 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_french-fries-snacks-fast-food_3558116", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_french_fries_soft_drink_takeaway_fastfood_food_4306498 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_french-fries-soft-drink-takeaway-fastfood-food_4306498", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_front_office_job_seeker_employee_unemployee_work_2620521 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_front_office_job_seeker_employee_unemployee_work_2620521", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_furniture_living_room_house_03_3799055 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_furniture_living_room_house-03_3799055", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_furniture_living_room_house_04_3799056 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_furniture_living_room_house-04_3799056", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_furniture_living_room_house_08_3799060 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_furniture_living_room_house-08_3799060", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_google_plus_one__1_ticket_68024 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_google_plus_one_+1_ticket_68024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_hamburger_burger_drink_soft_fastfood_fast_food_4306500 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_hamburger-burger-drink-soft-fastfood-fast-food_4306500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_hat_24_2875614 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_hat_24_2875614", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_hot_dogs_truck_food_delivery_street_3558109 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_hot-dogs-truck-food-delivery-street_3558109", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_Isolation_room_hospital_pandemic_6054258 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_Isolation_room_hospital_pandemic_6054258", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_media_cinema_clapperboard_social_media_network_4288563 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_media-cinema-clapperboard-social_media-network_4288563", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_movie_08_1277184 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_movie-08_1277184", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_Multimedia_Film_movie_cinema_multimedia_player_3841825 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_Multimedia_Film_movie_cinema_multimedia_player_3841825", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_popcorn_cinema_film_sweet_dessert_food_fastfood_4306481 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_popcorn-cinema-film-sweet-dessert-food-fastfood_4306481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_projector_cinema_movie_presentation_6427826 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_projector_cinema_movie_presentation_6427826", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_projector_cinema_movie_presentation_6427887 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_projector_cinema_movie_presentation_6427887", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_remove_ticket_49613 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_remove-ticket_49613", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_rotation_job_seeker_employee_unemployee_work_2620504 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_rotation_job_seeker_employee_unemployee_work_2620504", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_sausage_burger_bread_breakfast_food_3558099 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_sausage-burger-bread-breakfast-food_3558099", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_sausage_hotdog_snack_food_fast_fastfood_grill_4306511 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_sausage-hotdog-snack-food-fast-fastfood-grill_4306511", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_skill_job_seeker_employee_unemployee_work_2620501 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_skill_job_seeker_employee_unemployee_work_2620501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_St_Patricks_Day_ticket_Clover_Irish_Ireland_3_5830908 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_St_Patricks_Day_ticket_Clover_Irish_Ireland_3_5830908", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_systemmigratingdataservicecloud_4904829 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_systemmigratingdataservicecloud_4904829", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_telephone_24_7_customer_support_532791 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_telephone-24-7-customer-support_532791", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_ticket_carnival_coupon_cinema_festival_theater_3813284 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_ticket_carnival_coupon_cinema_festival_theater_3813284", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_video_512537 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_video_512537", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ke_an_nap {
            get {
                object obj = ResourceManager.GetObject("ke_an_nap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ke_cap_nha_dang2 {
            get {
                object obj = ResourceManager.GetObject("Ke-cap-nha-dang2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap khoai {
            get {
                object obj = ResourceManager.GetObject("khoai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mai_ben_em {
            get {
                object obj = ResourceManager.GetObject("mai-ben-em", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap members_icon {
            get {
                object obj = ResourceManager.GetObject("members-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rap_phim {
            get {
                object obj = ResourceManager.GetObject("rap-phim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tenet {
            get {
                object obj = ResourceManager.GetObject("tenet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Demi_Gods_and_Semi_Devils__2013_TV_series_ {
            get {
                object obj = ResourceManager.GetObject("The_Demi-Gods_and_Semi_Devils_(2013_TV_series)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unnamed {
            get {
                object obj = ResourceManager.GetObject("unnamed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
